---
openapi: 3.0.3
info:
  title: rails_api_base
  version: 1.0.0
servers: []
paths:
  "/api/v1/user":
    put:
      summary: update
      tags:
      - API::V1::User
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
        example: B_gWuAgOff4p_0oBedO19w
      - name: client
        in: header
        required: true
        schema:
          type: string
        example: khgkfl1nMhfhN9BpYjDPCw
      - name: uid
        in: header
        required: true
        schema:
          type: string
        example: lacie@farrell.example
      responses:
        '200':
          description: returns the user id
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 10
                  email: madison@schmitt.example
                  name: new username
                  username: new username
                  first_name: ''
                  last_name: ''
                  uid: madison@schmitt.example
                  provider: email
                  created_at: '2024-04-26T20:34:58.540Z'
                  updated_at: '2024-04-26T20:34:58.674Z'
        '400':
          description: returns the error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        email:
                          type: array
                          items:
                            type: string
                      required:
                      - email
                required:
                - errors
              example:
                errors:
                - email:
                  - is not an email
        '422':
          description: returns the missing params error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: A required param is missing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                  required:
                  - username
              required:
              - user
            example:
              user:
                username: new username
    get:
      summary: show
      tags:
      - API::V1::User
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
        example: t6P5tEbj_nHmkuy15b2UxQ
      - name: client
        in: header
        required: true
        schema:
          type: string
        example: "-FZ3xNhkoaoMr0HgzSxO3w"
      - name: uid
        in: header
        required: true
        schema:
          type: string
        example: vaughn@kovacek.example
      responses:
        '200':
          description: does not return a Set-Cookie Header
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 15
                  email: vaughn@kovacek.example
                  name: kendall.skiles
                  username: kendall.skiles
                  first_name: ''
                  last_name: ''
                  uid: vaughn@kovacek.example
                  provider: email
                  created_at: '2024-04-26T20:34:58.626Z'
                  updated_at: '2024-04-26T20:34:58.689Z'
        '404':
          description: returns status 404 not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Couldn't find the record
  "/api/v1/users":
    post:
      summary: create
      tags:
      - API::V1::Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                    username:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                  required:
                  - username
                  - email
                  - password
                  - password_confirmation
                  - first_name
                  - last_name
              required:
              - user
            example:
              user:
                email: test@example.com
                password: '12345678'
                password_confirmation: '12345678'
                username: test
                first_name: Johnny
                last_name: Perez
                admin_email: ''
      responses:
        '200':
          description: does not return a Set-Cookie Header
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 5
                  email: test@example.com
                  name: Johnny Perez
                  username: test
                  first_name: Johnny
                  last_name: Perez
                  uid: test@example.com
                  provider: email
                  created_at: '2024-04-26T20:34:57.901Z'
                  updated_at: '2024-04-26T20:34:57.979Z'
        '422':
          description: does not create a user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        nullable: true
                      email:
                        type: string
                      allow_password_change:
                        type: boolean
                      first_name:
                        type: string
                      last_name:
                        type: string
                      username:
                        type: string
                      created_at:
                        nullable: true
                      updated_at:
                        nullable: true
                      provider:
                        type: string
                      uid:
                        type: string
                      impersonated_by:
                        nullable: true
                    required:
                    - id
                    - email
                    - allow_password_change
                    - first_name
                    - last_name
                    - username
                    - created_at
                    - updated_at
                    - provider
                    - uid
                    - impersonated_by
                  errors:
                    type: object
                    properties:
                      password_confirmation:
                        type: array
                        items:
                          type: string
                      full_messages:
                        type: array
                        items:
                          type: string
                      email:
                        type: array
                        items:
                          type: string
                      password:
                        type: array
                        items:
                          type: string
                    required:
                    - full_messages
                required:
                - status
                - data
                - errors
              example:
                status: error
                data:
                  id: 
                  email: test@example.com
                  allow_password_change: false
                  first_name: Johnny
                  last_name: Perez
                  username: test
                  created_at: 
                  updated_at: 
                  provider: email
                  uid: test@example.com
                  impersonated_by: 
                errors:
                  password_confirmation:
                  - doesn't match Password
                  full_messages:
                  - Password is too short (minimum is 8 characters)
                  email:
                  - is not an email
                  password:
                  - is too short (minimum is 8 characters)
  "/api/v1/users/sign_in":
    post:
      summary: create
      tags:
      - API::V1::Session
      responses:
        '200':
          description: does not fail
          headers:
            access-token:
              schema:
                type: string
            expiry:
              schema:
                type: integer
            token-type:
              schema:
                type: string
            uid:
              schema:
                type: string
            client:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      name:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      uid:
                        type: string
                      provider:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - id
                    - email
                    - name
                    - username
                    - first_name
                    - last_name
                    - uid
                    - provider
                    - created_at
                    - updated_at
                required:
                - user
              example:
                user:
                  id: 14
                  email: jefferson@rau-bogisich.test
                  name: cordell_trantow
                  username: cordell_trantow
                  first_name: ''
                  last_name: ''
                  uid: jefferson@rau-bogisich.test
                  provider: email
                  created_at: '2024-04-26T20:34:58.289Z'
                  updated_at: '2024-04-26T20:34:58.361Z'
        '401':
          description: return errors upon failure
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                      required:
                      - message
                required:
                - errors
              example:
                errors:
                - message: Invalid login credentials. Please try again.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - user
            example:
              user:
                email: jefferson@rau-bogisich.test
                password: password
